import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <div className="min-h-screen max-[200vh] pt-[1rem] pb-[2rem] overflow-y-scroll  w-screen bg-black text-white flex items-center justify-center">
    {children}
   </div>
  );
}
